number_of_standard_tests_per_function = 3
number_of_edge_case_tests_per_function_parameter = 2
number_of_null_case_tests_per_function_parameter = 1
number_of_expected_error_tests_per_thrown_exception = 1