find_classes_declarations = r'.*class .*[{]'
find_functions = r'.*[(].*[)].*\{[^}]*}'
find_parameters = r'(?<=\()[^)]*(?=\))'
find_access_type = r'public|private|protected'
find_private_constructor = r'private\s+\w+\s*\(\)'
find_get_instance_method = r'static\s+\w+\s+getInstance\s*\(\)'
find_static_instance = r'private\s+static\s+\w+\s+\w+\s*;'